repos:
- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
  - id: black
    name: black
    always_run: true
    args: ["--line-length=120"]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8
    name: flake
    always_run: true
    args: ["--max-line-length=120"]
